plugins {
    id 'java'
    id 'checkstyle'
    id 'pmd'
    id 'jacoco'
    id 'nebula.lint' version '20.6.2'
}

group 'no.unit.marc'
version '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_21  // source-code version and must be <= targetCompatibility
    targetCompatibility = JavaVersion.VERSION_21 // bytecode target version
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

wrapper {
    distributionType = Wrapper.DistributionType.ALL
    gradleVersion = "8.14.5"
}

dependencies {
    implementation "org.apache.httpcomponents.core5:httpcore5:5.4.2"
    implementation "jakarta.ws.rs:jakarta.ws.rs-api:4.0.0"
    implementation "com.amazonaws:aws-lambda-java-core:1.4.0"
    implementation "com.google.code.gson:gson:2.14.0"
    implementation "com.github.BIBSYSDEV:marc21-xml-parser:2.11.5"
    implementation "org.slf4j:slf4j-api:2.0.18"
    implementation "commons-io:commons-io:2.17.0"// Forcing newer version being used in marc21-xml-parser
    implementation "com.github.bibsysdev:core:2.8.2"
    runtimeOnly "com.amazonaws:aws-lambda-java-log4j2:1.6.4"
    runtimeOnly "org.apache.logging.log4j:log4j-core:2.26.1"
    runtimeOnly "org.apache.logging.log4j:log4j-api:2.26.1"
    runtimeOnly "org.apache.logging.log4j:log4j-slf4j2-impl:2.26.1"
    testImplementation "org.mockito:mockito-core:5.23.0"
    testImplementation "org.hamcrest:hamcrest:3.0"
    testImplementation "org.junit.jupiter:junit-jupiter-api:6.1.0"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter:6.1.0"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:6.1.0"
}

gradleLint {
    rules = ['all-dependency']
    reportFormat = 'html'
    reportOnlyFixableViolations = true
}

tasks.named('test') {
    useJUnitPlatform()
    failFast = false
    testLogging {
        events 'skipped', 'failed'
    }
    finalizedBy jacocoTestReport
}

pmd {
    toolVersion = '7.25.0'
    ruleSetConfig = rootProject.resources.text.fromFile('config/pmd/ruleset.xml')
    ruleSets = []
    ignoreFailures = false
}

checkstyle {
    toolVersion = '13.6.0'
    configFile = rootProject.resources.text.fromFile('config/checkstyle/checkstyle.xml').asFile()
    showViolations = true
}

tasks.withType(Checkstyle).configureEach {
    reports {
        xml.required
        html.required
        html.stylesheet = rootProject.resources.text.fromFile('config/checkstyle/checkstyle-simple.xsl')
    }
}

jacocoTestReport {
    reports {
        html.outputLocation.set(layout.buildDirectory.dir("reports/jacoco"))
    }
}

jacoco {
    toolVersion = "0.8.15"
}

tasks.named('check').configure {
    dependsOn tasks.named('jacocoTestCoverageVerification')
}

tasks.named('jacocoTestCoverageVerification').configure {
    dependsOn tasks.named('jacocoTestReport')

    violationRules {
        rule {
            limit {
                counter = 'METHOD'
                value = 'COVEREDRATIO'
                minimum = 1.0
            }
        }

        rule {
            limit {
                counter = 'CLASS'
                value = 'COVEREDRATIO'
                minimum = 1.0
            }
        }
    }
}
