AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sets up lambda, api and base path mapping to fetch records from authority registry

Parameters:
  CustomDomain:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/api/domainName'
    Description: (Optional) Custom domain name for the API endpoint
  CustomDomainBasePath:
    Type: String
    Default: 'authority'
    Description: (Optional) Base path mapping in CustomDomain
    AllowedPattern: "^[a-zA-Z0-9$\\-_.+!*'(),]*$"
    ConstraintDescription: "May contain only letters, numbers and one of $-_.+!*'(),"
  SruEndpoint:
    Type: String
    Description: Url Endpoint to the SRU server
    Default: 'authority.bibsys.no/authority/rest/sru'

Conditions:
  HasDomainName: !Not [!Equals [!Ref CustomDomain, '']]
  HasCustomDomainBasePath: !Not [!Equals [!Ref CustomDomainBasePath, '']]

Globals:
  Function:
    Timeout: 20
  Api:
    Cors:
      AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
      AllowMethods: '''OPTIONS, GET'''
      AllowOrigin: '''*'''
    EndpointConfiguration: REGIONAL

Resources:

  AuthoritySruProxyApi:
    Type: AWS::Serverless::Api
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W64
            reason: "Skip access logging for artifacts bucket"
          - id: W68
            reason: "Skip encryption for artifacts bucket"
          - id: W69
            reason: "Skip bucket policy for artifacts bucket"
    Properties:
      Name: !Sub "${AWS::StackName}"
      StageName: v1
      EndpointConfiguration:
        Type: REGIONAL
      DefinitionBody:
        openapi: 3.0.3
        info:
          title: Authority SRU Proxy
          version: '1.0'
        paths:
          /:
            get:
              summary: Get record given by auth_id
              description: gets the record by auth_id
              consumes:
                - application/json
              produces:
                - application/json
              parameters:
                - in: query
                  name: auth_id
                  required: true
                  type: string
                  description: auth_id.
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetAuthoritySruRecordFunction.Arn}/invocations
                responses: { }
                httpMethod: POST
                type: AWS_PROXY
              responses:
                '200':
                  description: authority record
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/getAuthoritySruRecordResponseBody'
                '400':
                  description: Bad request.
                  content:
                    application/json:
                      schema:
                        title: 400 Bad request
                        type: object
                        properties:
                          error:
                            type: string
                            description: error message
                '500':
                  description: Internal server error.
                  content:
                    application/json:
                      schema:
                        title: 500 internal server error
                        type: object
                        properties:
                          error:
                            type: string
                            description: error message

        components:
          schemas:
            getAuthoritySruRecordResponseBody:
              title: authority record
              type: object
              properties:
                title:
                  type: string
                  description: authority record from Authority Registry

  GetAuthoritySruRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
          SRU_ENDPOINT: !Ref SruEndpoint
      Handler: no.unit.authority.GetAuthoritySruRecordHandler::handleRequest
      Runtime: java11
      MemorySize: 1024
      Events:
        GetAuthoritySruRecordEvent:
          Type: Api
          Properties:
            RestApiId: !Ref AuthoritySruProxyApi
            Method: get
            Path: /

  AuthoritySruProxyBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Condition: HasDomainName
    Properties:
      BasePath: !If
        - HasCustomDomainBasePath
        - !Ref CustomDomainBasePath
        - !Ref 'AWS::NoValue'
      DomainName: !Ref CustomDomain
      RestApiId: !Ref AuthoritySruProxyApi
      Stage: !Ref AuthoritySruProxyApi.Stage

Outputs:
  ApiEndpoint:
    Description: "Endpoint base URL for the API"
    Value: !If
      - HasDomainName
      - !Sub "https://${CustomDomain}/${CustomDomainBasePath}"
      - !Sub "https://${AuthoritySruProxyApi}.execute-api.${AWS::Region}.amazonaws.com/${AuthoritySruProxyApi.Stage}/"
