AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sets up lambda, api and base path mapping to fetch records from authority registry

Parameters:
  CustomDomain:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/api/domainName'
    Description: (Optional) Custom domain name for the API endpoint
  CustomDomainBasePath:
    Type: String
    Default: 'authority'
    Description: (Optional) Base path mapping in CustomDomain
    AllowedPattern: "^[a-zA-Z0-9$\\-_.+!*'(),]*$"
    ConstraintDescription: "May contain only letters, numbers and one of $-_.+!*'(),"
  SruEndpoint:
    Type: String
    Description: Url Endpoint to the SRU server
    Default: 'authority.bibsys.no/authority/rest/sru'

Conditions:
  HasDomainName: !Not [ !Equals [ !Ref CustomDomain, '' ] ]
  HasCustomDomainBasePath: !Not [ !Equals [ !Ref CustomDomainBasePath, '' ] ]

Globals:
  Function:
    Timeout: 20
  Api:
    Cors:
      AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
      AllowMethods: '''OPTIONS, GET'''
      AllowOrigin: '''*'''
    EndpointConfiguration: REGIONAL

Resources:

  AuthoritySruProxyAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 180

  AuthoritySruProxyApi:
    Type: AWS::Serverless::Api
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W64
            reason: "Skip access logging for artifacts bucket"
          - id: W68
            reason: "Skip encryption for artifacts bucket"
          - id: W69
            reason: "Skip bucket policy for artifacts bucket"
    Properties:
      Name: !Sub "${AWS::StackName}"
      StageName: v1
      EndpointConfiguration:
        Type: REGIONAL
      AccessLogSetting:
        DestinationArn: !GetAtt AuthoritySruProxyAccessLogGroup.Arn
        Format: '{ "apiId": "$context.apiId", "requestId": "$context.requestId", "integrationId": "$context.integration.requestId", "time": "$context.requestTime", "timeEpoch": "$context.requestTimeEpoch", "ip": "$context.identity.sourceIp", "method": "$context.httpMethod", "path": "$context.path", "status": "$context.status", "latency": "$context.integration.latency", "userAgent": "$context.identity.userAgent", "error.message": "$context.error.message" }'
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: ./docs/openapi.yaml

  GetAuthoritySruRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
          SRU_ENDPOINT: !Ref SruEndpoint
      Handler: no.unit.authority.GetAuthoritySruRecordHandler::handleRequest
      Runtime: java21
      MemorySize: 1024
      Events:
        GetAuthoritySruRecordEvent:
          Type: Api
          Properties:
            RestApiId: !Ref AuthoritySruProxyApi
            Method: get
            Path: /

  AuthoritySruProxyBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Condition: HasDomainName
    Properties:
      BasePath: !If
        - HasCustomDomainBasePath
        - !Ref CustomDomainBasePath
        - !Ref 'AWS::NoValue'
      DomainName: !Ref CustomDomain
      RestApiId: !Ref AuthoritySruProxyApi
      Stage: !Ref AuthoritySruProxyApi.Stage

Outputs:
  ApiEndpoint:
    Description: "Endpoint base URL for the API"
    Value: !If
      - HasDomainName
      - !Sub "https://${CustomDomain}/${CustomDomainBasePath}"
      - !Sub "https://${AuthoritySruProxyApi}.execute-api.${AWS::Region}.amazonaws.com/${AuthoritySruProxyApi.Stage}/"
